import PDFDocument from "pdfkit";
import type { AnalysisResultData } from "@/types";

export function generateReportPdf(result: AnalysisResultData): Buffer {
  const doc = new PDFDocument({
    size: "A4",
    margins: { top: 50, bottom: 50, left: 50, right: 50 },
  });

  const buffers: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => buffers.push(chunk));

  const isDf = result.predictionLabel === "deepfake";
  const score = result.prediction != null ? (result.prediction * 100).toFixed(1) : "N/A";
  const confidence = result.confidence != null ? (result.confidence * 100).toFixed(0) : "N/A";

  doc.fontSize(24).font("Helvetica-Bold").text("VeriSight", { align: "center" });
  doc.fontSize(10).font("Helvetica").fillColor("#666")
    .text("Deepfake Detection Report", { align: "center" })
    .moveDown(2);

  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#ccc").stroke().moveDown(1);

  doc.fontSize(16).font("Helvetica-Bold").fillColor("#000")
    .text("Detection Verdict", { align: "center" }).moveDown(0.5);
  doc.fontSize(28).font("Helvetica-Bold")
    .fillColor(isDf ? "#ef4444" : "#10b981")
    .text(isDf ? "DEEPFAKE DETECTED" : "AUTHENTIC", { align: "center" })
    .moveDown(1.5);

  const riskColor: Record<string, string> = {
    critical: "#ef4444", high: "#f59e0b", medium: "#3b82f6", low: "#10b981",
  };
  doc.fontSize(12).font("Helvetica").fillColor(riskColor[result.riskLevel ?? "low"] ?? "#666")
    .text(`Risk Level: ${(result.riskLevel ?? "unknown").toUpperCase()}`, { align: "center" })
    .moveDown(2);

  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#ccc").stroke().moveDown(1);

  doc.fontSize(14).font("Helvetica-Bold").fillColor("#000").text("Analysis Details").moveDown(0.5);

  const rows: [string, string][] = [
    ["Filename", result.filename],
    ["Deepfake Score", `${score}%`],
    ["Confidence", `${confidence}%`],
    ["Status", result.status],
    ["Frames Analyzed", `${result.framesAnalyzed ?? 0} / ${result.totalFrames ?? 0}`],
    ["Processing Time", result.processingTimeMs ? `${(result.processingTimeMs / 1000).toFixed(1)}s` : "N/A"],
    ["Date Analyzed", result.dateUploaded ? new Date(result.dateUploaded).toLocaleString() : "N/A"],
  ];

  const tableTop = doc.y;
  for (let i = 0; i < rows.length; i++) {
    const y = tableTop + i * 22;
    doc.fontSize(10).font("Helvetica-Bold").fillColor("#333").text(rows[i][0], 50, y, { width: 150 });
    doc.font("Helvetica").fillColor("#000").text(rows[i][1], 220, y, { width: 300 });
  }

  doc.moveDown(2);

  if (result.riskLevel) {
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#ccc").stroke().moveDown(1);
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#000").text("Recommendations").moveDown(0.5);

    const recs = getPdfRecommendations(result.riskLevel, isDf);
    doc.fontSize(10).font("Helvetica").fillColor("#333");
    for (const rec of recs) {
      doc.text(`\u2022 ${rec}`, { indent: 10, paragraphGap: 4 });
    }
  }

  doc.moveDown(3);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#ccc").stroke().moveDown(1);
  doc.fontSize(8).font("Helvetica").fillColor("#999")
    .text("Generated by VeriSight \u2014 AI-Powered Deepfake Detection", { align: "center" });

  doc.end();

  return Buffer.concat(buffers);
}

function getPdfRecommendations(riskLevel: string, isDf: boolean): string[] {
  if (!isDf) {
    return [
      "Content appears authentic. No significant deepfake indicators detected.",
      "Cross-verify the video source for contextual consistency.",
      "Stay vigilant as deepfake technology evolves rapidly.",
    ];
  }
  const recs = [
    "Do not share unverified content. Sharing deepfakes can spread misinformation.",
  ];
  if (riskLevel === "critical" || riskLevel === "high") {
    recs.push("Report suspicious content to platform moderators or authorities.");
  }
  recs.push("Examine visual artifacts, unnatural blinking, and audio-visual desync.");
  recs.push("Educate others about deepfake detection to improve digital literacy.");
  return recs;
}
