import Link from "next/link";

export const metadata = { title: "About | VeriSight" };

export default function AboutPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6 sm:py-16">
      <div className="text-center">
        <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-verisight-500/20 bg-verisight-500/10 px-4 py-1.5 text-xs font-medium text-verisight-300">
          <span className="flex h-2 w-2 rounded-full bg-verisight-400 animate-pulse" />
          About VeriSight
        </div>
        <h1 className="text-gradient mb-4 text-3xl font-bold tracking-tight sm:text-4xl">
          Understanding Deepfakes &amp; How We Detect Them
        </h1>
        <p className="mx-auto mb-12 max-w-xl text-gray-400">
          VeriSight is an AI-powered tool that analyzes videos to identify
          synthetic and manipulated media — helping you separate fact from fiction.
        </p>
      </div>

      <div className="space-y-6">
        <section className="glass glow-border rounded-2xl p-6 sm:p-8">
          <div className="mb-3 flex items-center gap-3">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-verisight-500/20">
              <svg className="h-5 w-5 text-verisight-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 10.5l4.72-4.72a.75.75 0 011.28.53v11.38a.75.75 0 01-1.28.53l-4.72-4.72M4.5 18.75h9a2.25 2.25 0 002.25-2.25v-9a2.25 2.25 0 00-2.25-2.25h-9A2.25 2.25 0 002.25 7.5v9a2.25 2.25 0 002.25 2.25z" />
              </svg>
            </div>
            <h2 className="text-lg font-semibold text-white">What Are Deepfakes?</h2>
          </div>
          <p className="text-sm leading-relaxed text-gray-400">
            Deepfakes are videos, images, or audio clips generated by artificial
            intelligence that convincingly replace one person&apos;s face, voice, or
            mannerisms with someone else&apos;s. Powered by deep learning techniques like
            autoencoders and generative adversarial networks (GANs), modern deepfakes
            can make it nearly impossible to tell real content from fabricated content
            with the naked eye.
          </p>
          <p className="mt-3 text-sm leading-relaxed text-gray-400">
            Common examples include face-swapped celebrity videos, voice-cloned phone
            calls, and manipulated political speeches. While there are legitimate
            uses in entertainment and film, the technology is increasingly used to
            deceive and manipulate audiences.
          </p>
        </section>

        <section className="glass glow-border rounded-2xl p-6 sm:p-8">
          <div className="mb-3 flex items-center gap-3">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-verisight-500/20">
              <svg className="h-5 w-5 text-verisight-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
              </svg>
            </div>
            <h2 className="text-lg font-semibold text-white">Why Do Deepfakes Matter?</h2>
          </div>
          <ul className="space-y-3 text-sm leading-relaxed text-gray-400">
            <li className="flex gap-2">
              <span className="mt-0.5 text-verisight-400">&bull;</span>
              <span><strong className="text-gray-300">Misinformation:</strong> Fake videos of public figures can spread false narratives faster than they can be corrected.</span>
            </li>
            <li className="flex gap-2">
              <span className="mt-0.5 text-verisight-400">&bull;</span>
              <span><strong className="text-gray-300">Fraud &amp; scams:</strong> Voice-cloned calls impersonating family or executives are used to steal money and credentials.</span>
            </li>
            <li className="flex gap-2">
              <span className="mt-0.5 text-verisight-400">&bull;</span>
              <span><strong className="text-gray-300">Reputation damage:</strong> Fabricated content can be used to blackmail, harass, or destroy careers and reputations.</span>
            </li>
            <li className="flex gap-2">
              <span className="mt-0.5 text-verisight-400">&bull;</span>
              <span><strong className="text-gray-300">Erosion of trust:</strong> As deepfakes become indistinguishable from reality, people may stop trusting genuine evidence.</span>
            </li>
          </ul>
        </section>

        <section className="glass glow-border rounded-2xl p-6 sm:p-8">
          <div className="mb-3 flex items-center gap-3">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-verisight-500/20">
              <svg className="h-5 w-5 text-verisight-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.75 3.104v5.714a2.25 2.25 0 01-.659 1.591L5 14.5M9.75 3.104c-.251.023-.501.05-.75.082m.75-.082a24.301 24.301 0 014.5 0m0 0v5.714c0 .597.237 1.17.659 1.591L19.8 15.3M14.25 3.104c.251.023.501.05.75.082M19.8 15.3l-1.57.393A9.065 9.065 0 0112 15a9.065 9.065 0 00-6.23.693L5 14.5m14.8.8l1.402 1.402c1.232 1.232.65 3.318-1.067 3.611A48.309 48.309 0 0112 21c-2.773 0-5.491-.235-8.135-.687-1.718-.293-2.3-2.379-1.067-3.61L5 14.5" />
              </svg>
            </div>
            <h2 className="text-lg font-semibold text-white">How VeriSight Works</h2>
          </div>
          <div className="space-y-4">
            {[
              ["1", "Paste a video URL", "Share any video link — YouTube, Vimeo, or a direct .mp4 — via the Upload page."],
              ["2", "AI analysis", "VeriSight sends the content to an AI model via OpenRouter, which inspects it for signs of synthetic generation."],
              ["3", "Get your verdict", "A deepfake score, confidence level, and risk rating are displayed on an instant visual gauge."],
              ["4", "Download the report", "A complete PDF forensic report with findings and recommendations is generated on demand."],
            ].map(([step, title, desc]) => (
              <div key={step} className="flex gap-4">
                <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-verisight-500 to-purple-500 text-sm font-bold text-white">
                  {step}
                </div>
                <div>
                  <h3 className="text-sm font-semibold text-white">{title}</h3>
                  <p className="mt-0.5 text-sm text-gray-400">{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>
      </div>

      <div className="mt-12 text-center">
        <Link
          href="/upload"
          className="glass glow-border inline-flex items-center gap-2 rounded-xl px-8 py-3.5 text-sm font-semibold text-white transition-all hover:bg-verisight-600/80"
        >
          Try It Yourself
          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5" />
          </svg>
        </Link>
      </div>
    </div>
  );
}