"""empty message

Revision ID: f7dfdd8614b9
Revises: 
Create Date: 2026-07-15 14:43:26.488881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7dfdd8614b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploaded_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_videos_user_id'), ['user_id'], unique=False)

    op.create_table('analysis_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('frames_analyzed', sa.Integer(), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['uploaded_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_results_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_results_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_results_video_id'), ['video_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_results_video_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_results_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_results_risk_level'))

    op.drop_table('analysis_results')
    with op.batch_alter_table('uploaded_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_videos_user_id'))

    op.drop_table('uploaded_videos')
    # ### end Alembic commands ###
